package potion

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// testCacheDir resolves the shared model cache used by tests and benchmarks:
// the library default (os.UserCacheDir()/go-potion), overridable via
// GO_POTION_HOME
func testCacheDir(tb testing.TB) string {
	cacheDir, err := resolveCacheDir()
	if err != nil {
		tb.Fatalf("Failed to resolve cache dir: %v", err)
	}
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		tb.Fatalf("Failed to create cache dir: %v", err)
	}
	return cacheDir
}

type EmbeddingTestCase struct {
	Text      string    `json:"text"`
	Embedding []float32 `json:"embedding"`
	Tokens    []int     `json:"tokens"`
}

func TestLoadAndEncode(t *testing.T) {
	// Reference samples are generated by validation/generate_tests.py using
	// the Python model2vec library
	for _, model := range Models() {
		t.Run(string(model), func(t *testing.T) {
			encoder, err := New(t.Context(), model)
			if err != nil {
				t.Fatalf("Failed to create encoder: %v", err)
			}

			samplesPath := filepath.Join("validation", "samples", fmt.Sprintf("%s.json", model))
			data, err := os.ReadFile(samplesPath)
			if err != nil {
				t.Fatalf("Failed to read %s: %v", samplesPath, err)
			}

			var testCases []EmbeddingTestCase
			if err := json.Unmarshal(data, &testCases); err != nil {
				t.Fatalf("Failed to parse %s: %v", samplesPath, err)
			}

			for _, tc := range testCases {
				t.Run(tc.Text, func(t *testing.T) {
					tokens, err := encoder.Tokenize(tc.Text)
					if err != nil {
						t.Fatalf("Failed to tokenize: %v", err)
					}

					if len(tokens) != len(tc.Tokens) {
						t.Errorf("Expected %d tokens, got %d", len(tc.Tokens), len(tokens))
						t.Errorf("Expected: %v", tc.Tokens)
						t.Errorf("Got: %v", tokens)
						return
					}

					for i, token := range tokens {
						if token != tc.Tokens[i] {
							t.Errorf("Token mismatch at position %d: expected %d, got %d", i, tc.Tokens[i], token)
						}
					}

					embedding, err := encoder.Encode(tc.Text)
					if err != nil {
						t.Fatalf("Failed to encode: %v", err)
					}

					if len(embedding) != len(tc.Embedding) {
						t.Errorf("Expected embedding length %d, got %d", len(tc.Embedding), len(embedding))
					}
					if len(embedding) != encoder.Dimensions() {
						t.Errorf("Dimensions() = %d, but embedding length is %d", encoder.Dimensions(), len(embedding))
					}

					// Compare with a small tolerance due to floating point differences
					const tolerance = 1e-6
					for j := range tc.Embedding {
						if abs(embedding[j]-tc.Embedding[j]) > tolerance {
							t.Errorf("At index %d: expected %f, got %f", j, tc.Embedding[j], embedding[j])
						}
					}
				})
			}
		})
	}
}

func TestZeroed(t *testing.T) {
	encoder, err := New(t.Context(), BASE2M)
	if err != nil {
		t.Fatalf("Failed to create encoder: %v", err)
	}

	// Test empty string encoding
	embedding, err := encoder.Encode("")
	if err != nil {
		t.Fatalf("Failed to encode empty string: %v", err)
	}

	// Check that all values are zero
	for i, v := range embedding {
		if v != 0 {
			t.Errorf("Expected zero at index %d, got %f", i, v)
		}
	}
}

func TestResolveCacheDir(t *testing.T) {
	t.Setenv("GO_POTION_HOME", "/env/dir")
	fromEnv, err := resolveCacheDir()
	if err != nil {
		t.Fatalf("resolveCacheDir with GO_POTION_HOME failed: %v", err)
	}
	if fromEnv != "/env/dir" {
		t.Errorf("Expected GO_POTION_HOME to be used, got %q", fromEnv)
	}

	t.Setenv("GO_POTION_HOME", "")
	def, err := resolveCacheDir()
	if err != nil {
		t.Fatalf("resolveCacheDir with GO_POTION_HOME unset failed: %v", err)
	}
	userCache, err := os.UserCacheDir()
	if err != nil {
		t.Skipf("no user cache dir on this system: %v", err)
	}
	if want := filepath.Join(userCache, "go-potion"); def != want {
		t.Errorf("Expected default cache dir %q, got %q", want, def)
	}
}

func TestEnsureFile(t *testing.T) {
	dir := t.TempDir()

	var requests int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if r.URL.Path == "/missing" {
			w.WriteHeader(http.StatusNotFound)
			return
		}
		w.Write([]byte("payload"))
	}))
	defer server.Close()

	dest := filepath.Join(dir, "model.bin")
	if err := ensureFile(t.Context(), server.URL, dest); err != nil {
		t.Fatalf("ensureFile failed: %v", err)
	}
	data, err := os.ReadFile(dest)
	if err != nil {
		t.Fatalf("Failed to read downloaded file: %v", err)
	}
	if string(data) != "payload" {
		t.Errorf("Expected %q, got %q", "payload", data)
	}
	if requests != 1 {
		t.Errorf("Expected 1 request, got %d", requests)
	}

	// An existing file must not be redownloaded
	if err := ensureFile(t.Context(), server.URL, dest); err != nil {
		t.Fatalf("ensureFile on existing file failed: %v", err)
	}
	if requests != 1 {
		t.Errorf("Expected no additional request for existing file, got %d total", requests)
	}

	// A failed download must leave nothing behind, temp files included
	if err := ensureFile(t.Context(), server.URL+"/missing", filepath.Join(dir, "missing.bin")); err == nil {
		t.Error("Expected error for 404 response")
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("Failed to read dir: %v", err)
	}
	if len(entries) != 1 || entries[0].Name() != "model.bin" {
		names := make([]string, 0, len(entries))
		for _, e := range entries {
			names = append(names, e.Name())
		}
		t.Errorf("Expected only model.bin in cache dir, got %v", names)
	}
}

// abs returns the absolute value of a float32
func abs(x float32) float32 {
	if x < 0 {
		return -x
	}
	return x
}

// bigTextChunks downloads big.txt if needed and returns it split into
// 256-word chunks
func bigTextChunks(b *testing.B, cacheDir string) []string {
	bigTextPath := filepath.Join(cacheDir, "big.txt")
	if _, err := os.Stat(bigTextPath); os.IsNotExist(err) {
		resp, err := http.Get("https://norvig.com/big.txt")
		if err != nil {
			b.Fatalf("Failed to download big.txt: %v", err)
		}
		defer resp.Body.Close()

		if resp.StatusCode != http.StatusOK {
			b.Fatalf("Failed to download big.txt: %s", resp.Status)
		}

		out, err := os.Create(bigTextPath)
		if err != nil {
			b.Fatalf("Failed to create big.txt: %v", err)
		}
		defer out.Close()

		if _, err := io.Copy(out, resp.Body); err != nil {
			b.Fatalf("Failed to write big.txt: %v", err)
		}
	}

	// Read the file
	content, err := os.ReadFile(bigTextPath)
	if err != nil {
		b.Fatalf("Failed to read big.txt: %v", err)
	}

	// Split into 256-word chunks
	words := strings.Fields(string(content))
	chunkSize := 256
	chunks := make([]string, 0, len(words)/chunkSize+1)
	for j := 0; j < len(words); j += chunkSize {
		end := j + chunkSize
		if end > len(words) {
			end = len(words)
		}
		chunks = append(chunks, strings.Join(words[j:end], " "))
	}
	return chunks
}

// benchModel returns the model the big-text benchmarks run with: BASE2M by
// default, overridable via GO_POTION_BENCH_MODEL (e.g. RETRIEVAL32M) to
// compare implementations on other models.
func benchModel(b *testing.B) Model {
	name := os.Getenv("GO_POTION_BENCH_MODEL")
	if name == "" {
		return BASE2M
	}
	model := Model(name)
	if _, ok := modelRepos[model]; !ok {
		b.Fatalf("Unknown GO_POTION_BENCH_MODEL %q", name)
	}
	return model
}

func BenchmarkEncodeBigText(b *testing.B) {
	cacheDir := testCacheDir(b)

	encoder, err := New(b.Context(), benchModel(b))
	if err != nil {
		b.Fatalf("Failed to create encoder: %v", err)
	}

	chunks := bigTextChunks(b, cacheDir)

	var totalBytes int64
	var totalVectors int64
	var totalTime time.Duration

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		start := time.Now()
		for _, chunk := range chunks {
			_, err := encoder.Encode(chunk)
			if err != nil {
				b.Fatalf("Failed to encode chunk: %v", err)
			}
			totalBytes += int64(len(chunk))
			totalVectors += 1
		}
		totalTime += time.Since(start)
	}

	// Calculate and report MB/s
	mbPerSecond := float64(totalBytes) / totalTime.Seconds() / 1024 / 1024
	b.ReportMetric(mbPerSecond, "MB/s")
	vectorsPerSecond := float64(totalVectors) / totalTime.Seconds()
	b.ReportMetric(vectorsPerSecond, "vectors/s")
}

// BenchmarkTokenizeBigText measures tokenization only (no embedding lookup),
// for comparison against other tokenizer implementations such as
// HuggingFace's Rust tokenizers library
func BenchmarkTokenizeBigText(b *testing.B) {
	cacheDir := testCacheDir(b)

	encoder, err := New(b.Context(), benchModel(b))
	if err != nil {
		b.Fatalf("Failed to create encoder: %v", err)
	}

	chunks := bigTextChunks(b, cacheDir)

	var totalBytes int64
	var totalTokens int64

	b.ResetTimer()
	start := time.Now()
	for i := 0; i < b.N; i++ {
		for _, chunk := range chunks {
			tokens, err := encoder.Tokenize(chunk)
			if err != nil {
				b.Fatalf("Failed to tokenize chunk: %v", err)
			}
			totalBytes += int64(len(chunk))
			totalTokens += int64(len(tokens))
		}
	}
	elapsed := time.Since(start)

	b.ReportMetric(float64(totalBytes)/elapsed.Seconds()/1024/1024, "MB/s")
	b.ReportMetric(float64(totalTokens)/elapsed.Seconds()/1e6, "Mtokens/s")
}

func TestTokenization(t *testing.T) {
	encoder, err := New(t.Context(), BASE2M)
	if err != nil {
		t.Fatalf("Failed to create encoder: %v", err)
	}

	// Test cases
	testCases := []struct {
		input    string
		expected []string // Expected word splits
	}{
		{
			input:    "Hello world!",
			expected: []string{"hello", "world", "!"},
		},
		{
			input:    "It's dangerous to go alone",
			expected: []string{"it", "'", "s", "dangerous", "to", "go", "alone"},
		},
	}

	wp, ok := encoder.tok.(*wordPieceTokenizer)
	if !ok {
		t.Fatalf("Expected BASE2M to use the WordPiece tokenizer, got %T", encoder.tok)
	}

	for _, tc := range testCases {
		t.Run(tc.input, func(t *testing.T) {
			// Get the actual word splits
			normalized := wp.normalizer.normalize(tc.input)
			actualWords := preTokenize(normalized)

			// Compare with expected
			if len(actualWords) != len(tc.expected) {
				t.Errorf("Expected %d words, got %d", len(tc.expected), len(actualWords))
				t.Errorf("Expected: %v", tc.expected)
				t.Errorf("Got: %v", actualWords)
			}

			// Get tokens for debugging
			tokens, err := encoder.Tokenize(tc.input)
			if err != nil {
				t.Fatalf("Failed to tokenize: %v", err)
			}

			// Print tokenization details
			t.Logf("Input: %s", tc.input)
			t.Logf("Words: %v", actualWords)
			t.Logf("Number of tokens: %d", len(tokens))
		})
	}
}
